spring:
  application:
    name: DMS_backend
  datasource:
    url: jdbc:postgresql://159.65.17.122:5432/dms_db
    username: senba
    password: 1qaz@WSX
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 7000
  servlet:
    context-path: "/api"
logging:
  level:
    root: info
    sql:
